name: arrowad_grade_eleven
description: A new Flutter project.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  stacked: ^2.0.2
  auto_route: ^1.0.2
  get_it: ^6.0.0
  injectable: ^1.2.2

  firebase_core: ^1.0.3
  firebase_auth: ^1.0.2
  cloud_firestore: ^1.0.4
  firebase_storage: ^8.0.2
  firebase_messaging: ^9.1.1

  flash: ^1.5.1

  syncfusion_flutter_pdfviewer: ^19.1.55-beta

  url_launcher: ^6.0.3
  font_awesome_flutter: ^9.0.0
  intl: ^0.17.0
  image_picker: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.12.2
  auto_route_generator: ^1.0.2
  injectable_generator: ^1.2.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Agency FB
      fonts:
        - asset: assets/fonts/agency_fb.ttf
        - asset: assets/fonts/agency_fb_bold.ttf
          weight: 700
